version: "3.8"

services:
  application:
    image: public.ecr.aws/l6z6v3j6/digital-land-performance:${DOCKER_APPLICATION_TAG}
    command: |
      bash -c " \
        sqlite3 digital-land.sqlite3 '.read digital-land-db-cleanup.sql' && \
        flask db upgrade && \
        gunicorn -b 0.0.0.0:$$PORT application.wsgi:app --timeout 120 --workers=2 --threads=4 --worker-class=gthread \
      "
    volumes:
      - .github/resources/digital-land-db-cleanup.sql:/app/digital-land-db-cleanup.sql

  zap:
    image: owasp/zap2docker-stable:${ZAP_VERSION-2.11.1}
    command: bash -c "zap.sh -cmd -addonupdate; zap.sh -cmd -autorun /zap/wrk/zap.yaml"
    volumes:
      - .:/zap/wrk
      - ./zap-working-dir/zap.log:/home/zap/.ZAP/zap.log
    depends_on:
      application:
        condition: service_healthy
