version: "3.8"

services:
  application:
    build:
      context: .
      target: live
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgis:postgis@database/postgis
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 1s
      timeout: 3s
      retries: 60
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgis/postgis
    environment:
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: postgis
    healthcheck:
      test: pg_isready -U postgis
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${DB_HOST_PORT-5432:}5432
