name: security-scan

on:
  #  schedule:
  #    - cron: "45 8 * * *"
  workflow_dispatch:
  push:
    branches:
      - feat/security-scans

env:
  APPLICATION: digital-land-performance
  DOCKER_REPO: public.ecr.aws/l6z6v3j6
  ZAP_VERSION: 2.11.1

jobs:
  staging-dynamic-audit:
    runs-on: ubuntu-latest
    env:
      DOCKER_APPLICATION_TAG: staging
    steps:
      - uses: actions/checkout@v2

      - name: setup
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker pull ${DOCKER_REPO}/${APPLICATION}:${DOCKER_APPLICATION_TAG}

      - name: attack
        run: make docker-staging-security-scan

      - name: parse report
        id: report
        run: |
          echo "::set-output name=alerts_info::$(jq -rc '[ .site[0].alerts[] | select(.riskcode == "0") | .riskcode ] | length' zap-report.json)"
          echo "::set-output name=alerts_low::$(jq -rc '[ .site[0].alerts[] | select(.riskcode == "1") | .riskcode ] | length' zap-report.json)"
          echo "::set-output name=alerts_medium::$(jq -rc '[ .site[0].alerts[] | select(.riskcode == "2") | .riskcode ] | length' zap-report.json)"
          echo "::set-output name=alerts_high::$(jq -rc '[ .site[0].alerts[] | select(.riskcode == "3") | .riskcode ] | length' zap-report.json)"
          echo "::set-output name=alerts_total::$(jq -rc '[ .site[0].alerts[] ] | length' zap-report.json)"

      - name: upload report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report.md
          path: zap-report.md

      - name: send report notification
        uses: slackapi/slack-github-action@v1
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: 'dl-developers'
          payload: |
            {
              "text": "Security Scan: Performance Prototype",
              "icon_emoji": ":zap:",
              "username": "SecurityScanner",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Security Scan: Performance Prototype"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "*TOTAL* ${{ steps.report.outputs.alerts_total }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*HIGH* ${{ steps.report.outputs.alerts_high }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*MEDIUM* ${{ steps.report.outputs.alerts_medium }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*LOW* ${{ steps.report.outputs.alerts_low }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*INFO* ${{ steps.report.outputs.alerts_info }}"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
